export interface MedicineCatalogItem {
  id: string;
  brandName: string;
  genericName: string;
  strength: string;
  dosageForm: "Tablet" | "Capsule" | "Syrup" | "Suspension" | "Injection" | "Drops";
  manufacturer: string;
  unitPrice: number;
  isAntibiotic: boolean;
  defaultInstructions: string;
  therapeuticClass: string;
}

export const BANGLADESH_MEDICINE_CATALOG: MedicineCatalogItem[] = [
  {
    id: "med-1",
    brandName: "Napa",
    genericName: "Paracetamol",
    strength: "500 mg",
    dosageForm: "Tablet",
    manufacturer: "Beximco Pharmaceuticals Ltd.",
    unitPrice: 1.20,
    isAntibiotic: false,
    defaultInstructions: "ভরা পেটে খাবেন (After food). জ্বর বা ব্যথার জন্য।",
    therapeuticClass: "Analgesic & Antipyretic",
  },
  {
    id: "med-2",
    brandName: "Napa Extra",
    genericName: "Paracetamol + Caffeine",
    strength: "500 mg + 65 mg",
    dosageForm: "Tablet",
    manufacturer: "Beximco Pharmaceuticals Ltd.",
    unitPrice: 2.50,
    isAntibiotic: false,
    defaultInstructions: "ভরা পেটে খাবেন (After food). মাথা ব্যথার জন্য প্রযোজ্য।",
    therapeuticClass: "Analgesic Combination",
  },
  {
    id: "med-3",
    brandName: "Ace",
    genericName: "Paracetamol",
    strength: "500 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 1.20,
    isAntibiotic: false,
    defaultInstructions: "ভরা পেটে সেব্য।",
    therapeuticClass: "Analgesic & Antipyretic",
  },
  {
    id: "med-4",
    brandName: "Ace Plus",
    genericName: "Paracetamol + Caffeine",
    strength: "500 mg + 65 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 2.50,
    isAntibiotic: false,
    defaultInstructions: "ভরা পেটে খাবেন।",
    therapeuticClass: "Analgesic Combination",
  },
  {
    id: "med-5",
    brandName: "Seclo",
    genericName: "Omeprazole",
    strength: "20 mg",
    dosageForm: "Capsule",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 6.00,
    isAntibiotic: false,
    defaultInstructions: "খাবারের ৩০ মিনিট আগে (Before food).",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
  },
  {
    id: "med-6",
    brandName: "Sergel",
    genericName: "Esomeprazole",
    strength: "20 mg",
    dosageForm: "Tablet",
    manufacturer: "Healthcare Pharmaceuticals Ltd.",
    unitPrice: 7.00,
    isAntibiotic: false,
    defaultInstructions: "খাবারের ৩০ মিনিট আগে পানির সাথে সেব্য।",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
  },
  {
    id: "med-7",
    brandName: "Maxpro",
    genericName: "Esomeprazole",
    strength: "20 mg",
    dosageForm: "Tablet",
    manufacturer: "Aristopharma Ltd.",
    unitPrice: 7.00,
    isAntibiotic: false,
    defaultInstructions: "সকালে ও রাতে খাবারের আধা ঘণ্টা আগে।",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
  },
  {
    id: "med-8",
    brandName: "Pantonix",
    genericName: "Pantoprazole",
    strength: "20 mg",
    dosageForm: "Tablet",
    manufacturer: "Incepta Pharmaceuticals Ltd.",
    unitPrice: 7.00,
    isAntibiotic: false,
    defaultInstructions: "খাবারের পূর্বে সেবন করুন।",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
  },
  {
    id: "med-9",
    brandName: "Ciprocin",
    genericName: "Ciprofloxacin",
    strength: "500 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 15.00,
    isAntibiotic: true,
    defaultInstructions: "অ্যান্টিবায়োটিক: কোর্স সম্পূর্ণ করুন (Do not stop midway). ভরা পেটে খাবেন।",
    therapeuticClass: "Fluoroquinolone Antibiotic",
  },
  {
    id: "med-10",
    brandName: "Zimax",
    genericName: "Azithromycin",
    strength: "500 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 35.00,
    isAntibiotic: true,
    defaultInstructions: "অ্যান্টিবায়োটিক: প্রতিদিন নির্দিষ্ট সময়ে খাবারের ১ ঘণ্টা আগে বা ২ ঘণ্টা পরে। কোর্স শেষ করুন।",
    therapeuticClass: "Macrolide Antibiotic",
  },
  {
    id: "med-11",
    brandName: "Monas",
    genericName: "Montelukast",
    strength: "10 mg",
    dosageForm: "Tablet",
    manufacturer: "The ACME Laboratories Ltd.",
    unitPrice: 17.50,
    isAntibiotic: false,
    defaultInstructions: "রাতে ঘুমানোর পূর্বে সেব্য (Night dose). অ্যাজমা ও অ্যালার্জির জন্য।",
    therapeuticClass: "Leukotriene Receptor Antagonist",
  },
  {
    id: "med-12",
    brandName: "Fexo",
    genericName: "Fexofenadine Hydrochloride",
    strength: "120 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 9.00,
    isAntibiotic: false,
    defaultInstructions: "খাবারের সাথে বা খালি পেটে সেব্য। অ্যালার্জির জন্য।",
    therapeuticClass: "Antihistamine",
  },
  {
    id: "med-13",
    brandName: "Alatrol",
    genericName: "Cetirizine Dihydrochloride",
    strength: "10 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 3.50,
    isAntibiotic: false,
    defaultInstructions: "রাতে খাবারের পর। ঘুম ঘুম ভাব হতে পারে।",
    therapeuticClass: "Antihistamine",
  },
  {
    id: "med-14",
    brandName: "Bicozin",
    genericName: "Vitamin B Complex + Zinc",
    strength: "Standard",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 2.75,
    isAntibiotic: false,
    defaultInstructions: "প্রতিদিন সকালে বা দুপুরে ভরা পেটে।",
    therapeuticClass: "Nutritional Supplement",
  },
  {
    id: "med-15",
    brandName: "Comprid",
    genericName: "Metformin Hydrochloride",
    strength: "500 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 4.50,
    isAntibiotic: false,
    defaultInstructions: "খাবারের ঠিক সাথে সাথে বা খাবারের পর সেব্য (ডায়াবেটিসের জন্য)।",
    therapeuticClass: "Oral Antidiabetic",
  },
  {
    id: "med-16",
    brandName: "Camlosart",
    genericName: "Amlodipine + Losartan Potassium",
    strength: "5 mg + 50 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 10.00,
    isAntibiotic: false,
    defaultInstructions: "প্রতিদিন সকালে নির্দিষ্ট সময়ে (উচ্চ রক্তচাপের জন্য)।",
    therapeuticClass: "Antihypertensive",
  },
  {
    id: "med-17",
    brandName: "Torax",
    genericName: "Ketorolac Tromethamine",
    strength: "10 mg",
    dosageForm: "Tablet",
    manufacturer: "Square Pharmaceuticals PLC",
    unitPrice: 12.00,
    isAntibiotic: false,
    defaultInstructions: "তীব্র ব্যথায় ভরা পেটে স্বল্প মেয়াদে সেব্য। গ্যাস্ট্রিকের ওষুধ সাথে রাখুন।",
    therapeuticClass: "NSAID",
  },
  {
    id: "med-18",
    brandName: "Gaviscon",
    genericName: "Sodium Alginate + Potassium Bicarbonate",
    strength: "Liquid",
    dosageForm: "Syrup",
    manufacturer: "Reckitt Benckiser",
    unitPrice: 220.00,
    isAntibiotic: false,
    defaultInstructions: "খাবারের পর এবং ঘুমানোর আগে ২ চামচ করে। হার্টবার্ন দূর করে।",
    therapeuticClass: "Antacid & Antireflux",
  },
];
